export const events = [
  {
    id: 1,
    category: "Music",
    title: "Jazz Night",
    tags: ["jazz"],
    date: "23 May 2024",
    location: "Jazz Club",
    image:
      "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/jazz-music-festival-design-template-572bf397edcab22ee9fb33b5c37c4a38_screen.jpg?ts=1578243428",
    description:
      "Jazz Night is a musical event featuring live performances by renowned jazz artists. The evening promises an enchanting blend of classic and contemporary jazz tunes in a cozy, intimate setting. Attendees will have the opportunity to enjoy a variety of jazz styles, from smooth and soulful melodies to upbeat and energetic rhythms.\n\nHighlights:\n- Live performances by top jazz musicians.\n- Special guest appearances.\n- A diverse selection of jazz genres.\n\nLocation Details:\nThe event will be held at the Jazz Club, a well-known venue famous for its excellent acoustics and comfortable seating. The club offers a perfect ambiance for enjoying live jazz music, with its dim lighting and stylish decor.\n\nVisitor Information:\n- Opening Hours: 7:00 PM - 10:00 PM\n- Admission: $30 for adults, $20 for students and seniors, free for children under 12.\n- Tickets can be purchased online or at the venue.\n- Refreshments and light snacks available at the club.\n\nWhether you are a jazz aficionado or a casual listener, Jazz Night offers a memorable experience filled with delightful music and a vibrant atmosphere.",
    position: { lat: 50.4501, lng: 30.5234 },
    likes: 120,
    isLiked: false,
  },
  {
    id: 123,
    category: "Art",
    title: "Art Exhibition",
    tags: ["paintings"],
    date: "28 May 2024",
    location: "Art Gallery",
    image:
      "https://img.freepik.com/free-vector/illustration-of-art-exhibition-poster_53876-18109.jpg",
    description:
      "The Art Exhibition\n is a curated event showcasing the works of contemporary artists from around the world. This exhibition aims to provide a platform for artists to present their latest creations and for art enthusiasts to experience diverse artistic expressions. Visitors will have the opportunity to view a wide range of mediums, including paintings, sculptures, installations, and digital art.\n\nHighlights:\n- Featuring renowned and emerging artists.\n- Special guided tours and artist talks.\n- Interactive installations and digital art displays.\n- Art pieces available for purchase.\n\nLocation Details:\nThe exhibition will be held at the prestigious Art Gallery, known for its spacious halls and excellent facilities for displaying artwork. The gallery is centrally located, making it easily accessible for visitors. The ambiance of the gallery provides a perfect setting for appreciating the fine details of each piece of art.\n\nVisitor Information:\n- Opening Hours: 10:00 AM - 7:00 PM\n- Admission: $20 for adults, $15 for students and seniors, free for children under 12.\n- Tickets can be purchased online or at the venue.\n- Refreshments available at the gallery café.\n\nWhether you are an art collector, a casual visitor, or someone looking to explore the art world, the Art Exhibition promises an enriching and inspiring experience.",
    position: { lat: 50.4547, lng: 30.5238 },
    likes: 33220,
    isLiked: false,
  },
  {
    id: 124,
    category: "Writers",
    title: "Art Exhibition",
    tags: ["poetry"],
    date: "28 May 2024",
    location: "Art Gallery",
    image:
      "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/jazz-music-festival-design-template-572bf397edcab22ee9fb33b5c37c4a38_screen.jpg?ts=1578243428",
    description:
      "The Art Exhibition\n is a curated event showcasing the works of contemporary artists from around the world. This exhibition aims to provide a platform for artists to present their latest creations and for art enthusiasts to experience diverse artistic expressions. Visitors will have the opportunity to view a wide range of mediums, including paintings, sculptures, installations, and digital art.\n\nHighlights:\n- Featuring renowned and emerging artists.\n- Special guided tours and artist talks.\n- Interactive installations and digital art displays.\n- Art pieces available for purchase.\n\nLocation Details:\nThe exhibition will be held at the prestigious Art Gallery, known for its spacious halls and excellent facilities for displaying artwork. The gallery is centrally located, making it easily accessible for visitors. The ambiance of the gallery provides a perfect setting for appreciating the fine details of each piece of art.\n\nVisitor Information:\n- Opening Hours: 10:00 AM - 7:00 PM\n- Admission: $20 for adults, $15 for students and seniors, free for children under 12.\n- Tickets can be purchased online or at the venue.\n- Refreshments available at the gallery café.\n\nWhether you are an art collector, a casual visitor, or someone looking to explore the art world, the Art Exhibition promises an enriching and inspiring experience.",
    position: { lat: 50.4519, lng: 30.527 },
    likes: 1222,
    isLiked: false,
  },
  {
    "id": 2,
    "category": "Theater",
    "title": "Shakespeare in the Park",
    "tags": ["theater", "Shakespeare"],
    "date": "25 May 2024",
    "location": "Central Park",
    "image": "https://example.com/shakespeare_park.jpg",
    "description": "Experience the magic of Shakespeare with live performances of his most beloved plays. Set in the picturesque Central Park, this event brings classic literature to life in a beautiful outdoor setting. Enjoy the timeless stories of love, betrayal, and intrigue under the stars.\n\nHighlights:\n- Performances of Shakespeare's famous plays.\n- Outdoor setting with a picturesque backdrop.\n- Family-friendly event.\n\nLocation Details:\nCentral Park offers a serene environment perfect for enjoying outdoor theater. Bring a blanket or chair and settle in for an evening of timeless entertainment.\n\nVisitor Information:\n- Opening Hours: 6:00 PM - 9:00 PM\n- Admission: Free for all ages.\n- Refreshments available at nearby food stalls.\n\nJoin us for an unforgettable evening of Shakespearean drama in the heart of the city.",
    "position": { "lat": 40.785091, "lng": -73.968285 },
    "likes": 200,
    "isLiked": false
  },
  {
    "id": 3,
    "category": "Art",
    "title": "Modern Art Exhibition",
    "tags": ["art", "exhibition"],
    "date": "27 May 2024",
    "location": "City Art Gallery",
    "image": "https://example.com/modern_art.jpg",
    "description": "Discover the latest trends in contemporary art at the Modern Art Exhibition. Featuring works by emerging and established artists, this exhibition showcases a variety of styles and mediums. Explore the creativity and innovation that define the modern art scene.\n\nHighlights:\n- Artworks by renowned and upcoming artists.\n- A diverse range of styles and mediums.\n- Interactive installations and live art demonstrations.\n\nLocation Details:\nThe City Art Gallery is known for its spacious and well-lit exhibition halls, providing the perfect environment to appreciate modern art.\n\nVisitor Information:\n- Opening Hours: 10:00 AM - 6:00 PM\n- Admission: $15 for adults, $10 for students and seniors.\n- Tickets available online and at the gallery.\n- Guided tours available on request.\n\nImmerse yourself in the vibrant world of modern art and get inspired by the creativity on display.",
    "position": { "lat": 34.052235, "lng": -118.243683 },
    "likes": 150,
    "isLiked": false
  },
  {
    "id": 4,
    "category": "Film",
    "title": "Outdoor Movie Night",
    "tags": ["film", "outdoor"],
    "date": "29 May 2024",
    "location": "Riverside Park",
    "image": "https://example.com/outdoor_movie.jpg",
    "description": "Join us for a relaxing evening under the stars with our Outdoor Movie Night event. Enjoy a classic film in the open air, surrounded by the beauty of Riverside Park. Bring a blanket and your favorite snacks for a cozy and memorable night out.\n\nHighlights:\n- Screening of a classic movie.\n- Family-friendly atmosphere.\n- Free popcorn and soft drinks.\n\nLocation Details:\nRiverside Park offers a scenic location for outdoor events, with ample space for seating and a great view of the screen from any spot.\n\nVisitor Information:\n- Opening Hours: 8:00 PM - 10:00 PM\n- Admission: Free for all ages.\n- Bring your own seating or rent a chair at the park.\n- Refreshments available at nearby food trucks.\n\nDon't miss this chance to enjoy a beloved film in a unique and beautiful setting.",
    "position": { "lat": 37.774929, "lng": -122.419418 },
    "likes": 180,
    "isLiked": false
  },
  {
    "id": 5,
    "category": "Dance",
    "title": "Salsa Dance Party",
    "tags": ["dance", "salsa"],
    "date": "31 May 2024",
    "location": "Dance Hall",
    "image": "https://example.com/salsa_dance.jpg",
    "description": "Get ready to move your feet at the Salsa Dance Party! Whether you're a seasoned dancer or a beginner, this event is perfect for anyone looking to have fun and learn some new moves. Enjoy a lively evening of salsa music, dancing, and socializing.\n\nHighlights:\n- Live salsa band and DJ.\n- Dance lessons for beginners.\n- Dance contests with prizes.\n\nLocation Details:\nThe Dance Hall is a popular venue with a spacious dance floor and great sound system, creating the perfect environment for a night of salsa dancing.\n\nVisitor Information:\n- Opening Hours: 7:00 PM - 11:00 PM\n- Admission: $25 for adults, $15 for students.\n- Tickets available online and at the door.\n- Refreshments and drinks available at the bar.\n\nCome and experience the energy and excitement of salsa dancing at our Salsa Dance Party!",
    "position": { "lat": 40.712776, "lng": -74.005974 },
    "likes": 160,
    "isLiked": false
  },
  {
    "id": 6,
    "category": "Food",
    "title": "Gourmet Food Festival",
    "tags": ["food", "festival"],
    "date": "2 June 2024",
    "location": "Food Plaza",
    "image": "https://example.com/gourmet_food.jpg",
    "description": "Indulge in a culinary adventure at the Gourmet Food Festival. This event brings together top chefs and food vendors to showcase their delicious creations. Sample a variety of gourmet dishes, desserts, and beverages in a vibrant and festive atmosphere.\n\nHighlights:\n- Tastings from renowned chefs.\n- Cooking demonstrations and workshops.\n- Live music and entertainment.\n\nLocation Details:\nFood Plaza is a spacious venue known for hosting food events, offering plenty of seating and a lively ambiance perfect for a food festival.\n\nVisitor Information:\n- Opening Hours: 11:00 AM - 8:00 PM\n- Admission: $20 for adults, $10 for children under 12.\n- Tickets available online and at the entrance.\n- Free samples and special discounts on food purchases.\n\nJoin us for a day of gourmet delights and discover new flavors at the Gourmet Food Festival.",
    "position": { "lat": 51.507351, "lng": -0.127758 },
    "likes": 220,
    "isLiked": false
  },
  {
    "id": 7,
    "category": "Concert",
    "title": "Rock Night",
    "tags": ["rock", "concert"],
    "date": "5 June 2024",
    "location": "Left Bank Arena",
    "image": "https://example.com/rock_night.jpg",
    "description": "Rock Night is the ultimate event for rock music fans, featuring live performances from top rock bands. Get ready for an electrifying evening with powerful guitar riffs and energetic vocals.\n\nHighlights:\n- Performances by popular rock bands.\n- Special guest appearances.\n- Merchandising stands with band memorabilia.\n\nLocation Details:\nLeft Bank Arena is a large venue known for hosting major music events, with excellent acoustics and a dynamic atmosphere.\n\nVisitor Information:\n- Opening Hours: 8:00 PM - 11:00 PM\n- Admission: $40 for adults, $25 for students.\n- Tickets available online and at the arena.\n- Refreshments and snacks available.\n\nJoin us for an unforgettable night of rock music and excitement.",
    "position": { "lat": 50.4536, "lng": 30.5238 },
    "likes": 300,
    "isLiked": false
  },
  {
    "id": 8,
    "category": "Festival",
    "title": "Summer Food Festival",
    "tags": ["food", "festival"],
    "date": "10 June 2024",
    "location": "Left Bank Park",
    "image": "https://example.com/summer_food_festival.jpg",
    "description": "The Summer Food Festival is a celebration of culinary delights, featuring food stalls from various cuisines, cooking demonstrations, and live music. Enjoy a wide range of delicious dishes and beverages in a lively outdoor setting.\n\nHighlights:\n- Diverse food stalls and vendors.\n- Cooking workshops and live demos.\n- Live music and entertainment.\n\nLocation Details:\nLeft Bank Park offers a spacious and green environment perfect for outdoor festivals, with plenty of seating and picnic areas.\n\nVisitor Information:\n- Opening Hours: 12:00 PM - 8:00 PM\n- Admission: $10 for adults, free for children under 12.\n- Tickets available online and at the entrance.\n- Family-friendly event with activities for kids.\n\nCome and enjoy a day of gourmet food, music, and fun at the Summer Food Festival.",
    "position": { "lat": 50.4574, "lng": 30.6294 },
    "likes": 250,
    "isLiked": false
  },
  {
    "id": 9,
    "category": "Sports",
    "title": "Beach Volleyball Tournament",
    "tags": ["sports", "volleyball"],
    "date": "15 June 2024",
    "location": "Left Bank Beach",
    "image": "https://example.com/beach_volleyball.jpg",
    "description": "Join us for an exciting Beach Volleyball Tournament at Left Bank Beach. Watch teams compete for the championship in a fun and competitive environment. Enjoy the sun, sand, and sportsmanship.\n\nHighlights:\n- Competitive volleyball matches.\n- Beachside activities and games.\n- Refreshments and food stalls.\n\nLocation Details:\nLeft Bank Beach provides a beautiful setting with sandy courts and a vibrant atmosphere, perfect for beach volleyball.\n\nVisitor Information:\n- Opening Hours: 10:00 AM - 6:00 PM\n- Admission: Free for spectators.\n- Team registration required for participants.\n- Beach gear and refreshments available.\n\nDon't miss this chance to witness thrilling beach volleyball action and enjoy a day at the beach.",
    "position": { "lat": 50.4590, "lng": 30.6225 },
    "likes": 180,
    "isLiked": false
  },
  {
    "id": 10,
    "category": "Culture",
    "title": "Ukrainian Folk Music Festival",
    "tags": ["music", "folk"],
    "date": "20 June 2024",
    "location": "Left Bank Cultural Center",
    "image": "https://example.com/folk_music_festival.jpg",
    "description": "Celebrate Ukrainian heritage at the Ukrainian Folk Music Festival. Enjoy performances of traditional folk music, dance, and cultural activities. Experience the rich cultural heritage of Ukraine in a festive atmosphere.\n\nHighlights:\n- Live folk music performances.\n- Traditional Ukrainian dances.\n- Cultural workshops and activities.\n\nLocation Details:\nLeft Bank Cultural Center is known for hosting cultural events, providing a perfect venue with excellent acoustics and comfortable seating.\n\nVisitor Information:\n- Opening Hours: 1:00 PM - 9:00 PM\n- Admission: $20 for adults, $10 for students and seniors.\n- Tickets available online and at the center.\n- Ukrainian food and crafts available for purchase.\n\nJoin us for a day of music, dance, and culture at the Ukrainian Folk Music Festival.",
    "position": { "lat": 50.4562, "lng": 30.6283 },
    "likes": 220,
    "isLiked": false
  },
  {
    "id": 11,
    "category": "Technology",
    "title": "Tech Innovation Expo",
    "tags": ["technology", "expo"],
    "date": "25 June 2024",
    "location": "Left Bank Exhibition Hall",
    "image": "https://example.com/tech_expo.jpg",
    "description": "Discover the latest advancements in technology at the Tech Innovation Expo. Featuring exhibits from leading tech companies, interactive demos, and keynote speeches from industry experts. Stay ahead of the curve with insights into the future of technology.\n\nHighlights:\n- Exhibits from top tech companies.\n- Interactive technology demos.\n- Keynote speeches and panel discussions.\n\nLocation Details:\nLeft Bank Exhibition Hall is a modern venue with state-of-the-art facilities, ideal for hosting large-scale expos and conferences.\n\nVisitor Information:\n- Opening Hours: 9:00 AM - 6:00 PM\n- Admission: $50 for adults, $30 for students.\n- Tickets available online and at the venue.\n- Networking opportunities and business lounges.\n\nDon't miss this chance to explore cutting-edge technology and network with industry leaders at the Tech Innovation Expo.",
    "position": { "lat": 50.4531, "lng": 30.6251 },
    "likes": 280,
    "isLiked": false
  }
];

export const center = {
  lat: 50.4501,
  lng: 30.5234,
};
